export const PUZZLE_TITLE_UPDATED = 'entity/Puzzles/PUZZLE_TITLE_UPDATED';
export const PUZZLE_NOTES_EDITED = 'entity/Puzzles/PUZZLE_NOTES_EDITED';
export const PUZZLE_SYMMETRY_SET = 'entity/Puzzles/PUZZLE_SYMMETRY_SET';
export const SQUARES_BLACK_SET = 'entity/Puzzles/SQUARES_BLACK_SET';
export const SQUARES_BLACK_TOGGLED = 'entity/Puzzles/SQUARES_BLACK_TOGGLED';
export const SYMMETRY_MODE_NONE = 'SYMMETRY_NONE';
export const SYMMETRY_MODE_DIAGONAL = 'SYMMETRY_DIAGONAL';
